language: java
install: mvn clean install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
jdk:
  - openjdk8
branches:
  only:
   - jch-v2
deploy:
  provider: script
  script: "cp .maven.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
before_install:
   - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
   - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
